"""update flight model

Revision ID: 42d0961a7f5c
Revises: 
Create Date: 2025-05-08 20:38:02.357030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d0961a7f5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airline', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('terminal', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('aircraft_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_in_counter', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('boarding_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.drop_column('boarding_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('check_in_counter')
        batch_op.drop_column('aircraft_type')
        batch_op.drop_column('terminal')
        batch_op.drop_column('airline')

    # ### end Alembic commands ###
